### ISSUE TITLE
node_modules should be in gitignore

### ISSUE THREAD

**Issue by nilbuild** [wuuanito/Task-Tracker#1]
Adding `node_modules` to your repository would result in:

- Massive repo size, slow pulls and pushes
- Potential for horrible merges (conflicts when someone opens a PR, for example).
- Unreadably noisy diffs in PRs

Just push `package-lock.json` and it should be enough.

**Comment by wuuanito** [comment]
Thank you very much for your comment, I will take it into account, you are an example to follow.
